### ISSUE TITLE
Template format error: Unrecognized resource types: [AWS::SES::ReceiptRuleSet, AWS::SES::ReceiptRule]

### ISSUE THREAD

**Issue by willhumphreys** [seeebiii/ses-email-forwarding#448]
I'm getting this error when I do a `cdk deploy`. I'm kind of new to the ckd and typescript so possibly I'm just making some beginner error 

VitaminsStack failed: Error [ValidationError]: Template format error: Unrecognized resource types: [AWS::SES::ReceiptRuleSet, AWS::SES::ReceiptRule]
    at Request.extractError (/opt/homebrew/Cellar/aws-cdk/2.64.0/libexec/lib/node_modules/aws-cdk/lib/index.js:31:33843)
    at Request.callListeners (/opt/homebrew/Cellar/aws-cdk/2.64.0/libexec/lib/node_modules/aws-cdk/lib/index.js:31:76646)
    at Request.emit (/opt/homebrew/Cellar/aws-cdk/2.64.0/libexec/lib/node_modules/aws-cdk/lib/index.js:31:76094)
    at Request.emit (/opt/homebrew/Cellar/aws-cdk/2.64.0/libexec/lib/node_modules/aws-cdk/lib/index.js:31:182419)
    at Request.transition (/opt/homebrew/Cellar/aws-cdk/2.64.0/libexec/lib/node_modules/aws-cdk/lib/index.js:31:175971)
    at AcceptorStateMachine.runT

**Comment by seeebiii** [comment]
Hi @willhumphreys , thanks for your issue! That's an interesting error. The resource types look correct as they still exist in CloudFormation:
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ses-receiptruleset.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ses-receiptrule.html

If you can give me some more information what you're building or some example code how you're integrating the library, I might be able to help a bit better.

One idea I have is that something changed in the newer CDK versions and this library here didn't catch up properly. I need to test that but I won't find time to do this until Sunday.

**Comment by willhumphreys** [comment]
I think the issue is that I am trying to deploy to eu-central-1 and that region doesn't support all the email functionality.
